# Use official Node.js image
FROM node:20-slim

# Create app directory
WORKDIR /app

# Copy bot code
COPY ./frontend/app/package.json ./package.json

# Install dependencies
RUN npm install


# Copy bot code
COPY ./frontend/app/ ./


# Expose port and start bot
EXPOSE 5173
CMD ["npm", "run", "dev","--", "--host", "0.0.0.0"]