FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates

# Download the latest installer
ADD https://astral.sh/uv/install.sh /uv-installer.sh

# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"
WORKDIR /app
COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./.env ./.env

RUN mkdir polylogue
RUN mkdir config
RUN mkdir output

COPY polylogue/ ./polylogue/
COPY config/ ./config/



EXPOSE 8000
# CMD ["python", "-m", "uvicorn", "polylogue.app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
CMD ["sh", "-c", "uvicorn polylogue.app.main:app --host 0.0.0.0 --port 8000 --reload || tail -f /dev/null"]


